name: Sync to repoB

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repoA
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "theonlyaswin"
          git config --global user.email "aswin.contactme@gmail.com"

      - name: Add repoB as a remote
        run: git remote add repoB https://x-access-token:${{ secrets.GH_PAT }}@github.com/theonlyaswin/repoB.git

      - name: Push changes to repoB
        run: git push repoB main --force
